doc-warnings: yes
test-warnings: no
strictness: medium
max-line-length: 90
uses:
    - flask
autodetect: yes
pylint:
  disable:
    - cyclic-import
    - invalid-name
    - logging-format-interpolation
  options:
    docstring-min-length: 10
pep8:
  full: true
ignore-paths:
    - docs
<<<<<<< 4386977960aaa513607464e437084f2dc7435647
<<<<<<< a5f33fecd81ce1c86859856bdc1a3a4f73b7893c
    - caravel/migrations/env.py
    - caravel/ascii_art.py
=======
    - dashed/migrations/env.py
    - dashed/ascii_art.py
>>>>>>> [panoramix] -> [dashed]
=======
<<<<<<< HEAD
    - dashed/migrations/env.py
    - dashed/ascii_art.py
=======
    - caravel/migrations/env.py
    - caravel/ascii_art.py
>>>>>>> c2baa53b060cda4352582d238f53369e3f7773d0
>>>>>>> merge from caravel/master
ignore-patterns:
    - ^example/doc_.*\.py$
    - (^|/)docs(/|$)
