doc-warnings: yes
test-warnings: no
strictness: medium
max-line-length: 90
uses:
    - flask
autodetect: yes
pylint:
  disable:
    - cyclic-import
    - invalid-name
    - logging-format-interpolation
  options:
    docstring-min-length: 10
pep8:
  full: true
ignore-paths:
    - docs
<<<<<<< a5f33fecd81ce1c86859856bdc1a3a4f73b7893c
    - caravel/migrations/env.py
    - caravel/ascii_art.py
=======
    - dashed/migrations/env.py
    - dashed/ascii_art.py
>>>>>>> [panoramix] -> [dashed]
ignore-patterns:
    - ^example/doc_.*\.py$
    - (^|/)docs(/|$)
