language: python
python:
  - "2.7"
  - "3.4"
cache:
  directories:
    - $HOME/.wheelhouse/
before_install:
  - npm install -g npm@'>=2.7.1'
install:
<<<<<<< HEAD
  - pip wheel -w $HOME/.wheelhouse -f $HOME/.wheelhouse -r requirements.txt
  - pip install --find-links=$HOME/.wheelhouse --no-index -rrequirements.txt
  - python setup.py install
  - cd dashed/assets
=======
  - pip wheel -w $HOME/.wheelhouse -f $HOME/.wheelhouse .
  - pip install --find-links=$HOME/.wheelhouse --no-index .
  - pip install --find-links=$HOME/.wheelhouse --no-index -r dev-reqs.txt
  - cd caravel/assets
  - npm --version
>>>>>>> c2baa53b060cda4352582d238f53369e3f7773d0
  - npm install
  - npm run lint
  - npm run prod
  - cd $TRAVIS_BUILD_DIR
script: bash run_tests.sh
after_success:
  - coveralls
<<<<<<< HEAD
  - cd dashed/assets
  - npm run lint
=======
>>>>>>> c2baa53b060cda4352582d238f53369e3f7773d0
