language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
cache:
  directories:
    - $HOME/.wheelhouse/
before_install:
  - npm install -g npm@'>=2.7.1'
install:
<<<<<<< a5f33fecd81ce1c86859856bdc1a3a4f73b7893c
  - pip wheel -w $HOME/.wheelhouse -f $HOME/.wheelhouse .
  - pip install --find-links=$HOME/.wheelhouse --no-index .
  - pip install -r dev-reqs.txt
  - cd caravel/assets
  - npm --version
=======
  - pip wheel -w $HOME/.wheelhouse -f $HOME/.wheelhouse -r requirements.txt
  - pip install --find-links=$HOME/.wheelhouse --no-index -rrequirements.txt
  - python setup.py install
  - cd dashed/assets
>>>>>>> [panoramix] -> [dashed]
  - npm install
  - npm run lint
  - npm run prod
  - cd $TRAVIS_BUILD_DIR
script: bash run_tests.sh
after_success:
  - coveralls
<<<<<<< a5f33fecd81ce1c86859856bdc1a3a4f73b7893c
=======
  - cd dashed/assets
  - npm run lint
>>>>>>> [panoramix] -> [dashed]
